### ISSUE TITLE
`parse_input` does not currently support Generators

### ISSUE THREAD

**Issue by ionite34** [fergusch/advent-cli#1]
It is quite common to use generators to handle input parsing:
```python
def parse_input(lines: list[str]):
    for line in lines:
       yield re.match('...', line).groups()
```

Currently, this does not work as the runner passes the same generator into Part 1 and Part 2, which is exhausted in Part 2 as it has already been iterated in Part 1.

This can be implemented relatively easily if desired by detecting a Generator with `isinstance` and making a copy for Part 2.

**Comment by fergusch** [comment]
I'm a little rusty with generators, but I think this should work: https://github.com/fergusch/advent-cli/commit/afce205c19c569ee5e7485e8c1d731aaa2d67b2a

Thoughts?

**Comment by ionite34** [comment]
> I'm a little rusty with generators, but I think this should work: [afce205](https://github.com/fergusch/advent-cli/commit/afce205c19c569ee5e7485e8c1d731aaa2d67b2a)
> 
> Thoughts?

Thanks for the quick implementation!

This is probably more appropriate than `GeneratorType`:
```python
from collections.abc import Generator

if isinstance(data, Generator):
```

But otherwise, everything else looks good!

**Comment by fergusch** [comment]
Awesome, changes will be included in the next release. Closing this issue.
